from sqlalchemy import Column, Integer, String, Boolean, Float, DateTime, Date, INTEGER, VARCHAR, DATE, DATETIME, BOOLEAN, FLOAT
from .foundation import Base


class TannersAutoGeneratedTable(Base):
    __tablename__ = "tannersautogeneratedtable"

    id = Column(INTEGER, primary_key=True, index=True)
    tech_name = Column(VARCHAR, primary_key=False, index=None)
    job_number = Column(DATE, primary_key=False, index=None)
    purchase_date = Column(DATE, primary_key=False, index=None)
    vendor = Column(VARCHAR, primary_key=False, index=None)
    tax = Column(FLOAT, primary_key=False, index=None)
    subtotal = Column(FLOAT, primary_key=False, index=None)
    total_cost = Column(FLOAT, primary_key=False, index=None)

class TannersSecondAutoGeneratedTable(Base):
    __tablename__ = "tannerssecondautogeneratedtable"

    id = Column(INTEGER, primary_key=True, index=True)
    tech_name = Column(VARCHAR, primary_key=False, index=None)
    job_number = Column(DATE, primary_key=False, index=None)
    purchase_date = Column(DATE, primary_key=False, index=None)
    vendor = Column(VARCHAR, primary_key=False, index=None)
    tax = Column(FLOAT, primary_key=False, index=None)
    subtotal = Column(FLOAT, primary_key=False, index=None)
    total_cost = Column(FLOAT, primary_key=False, index=None)

class TannersThirdAutoGeneratedTable(Base):
    __tablename__ = "tannersthirdautogeneratedtable"

    id = Column(INTEGER, primary_key=True, index=True)
    tech_name = Column(VARCHAR, primary_key=False, index=None)
    job_number = Column(VARCHAR, primary_key=False, index=None)
    purchase_date = Column(DATE, primary_key=False, index=None)
    vendor = Column(VARCHAR, primary_key=False, index=None)
    tax = Column(FLOAT, primary_key=False, index=None)
    subtotal = Column(FLOAT, primary_key=False, index=None)
    total_cost = Column(FLOAT, primary_key=False, index=None)
