from pydantic import BaseModel
from datetime import datetime as DateTime
from datetime import date as Date
from typing import Literal, Any
from datetime import date
from datetime import datetime
data_types = Literal["str", "int", "float", "bool", "Date", "DateTime"]


class TannersAutoGeneratedTable_schema(BaseModel):
    tech_name: str
    job_number: date
    purchase_date: date
    vendor: str
    tax: float
    subtotal: float
    total_cost: float

class TannersSecondAutoGeneratedTable_schema(BaseModel):
    tech_name: str
    job_number: date
    purchase_date: date
    vendor: str
    tax: float
    subtotal: float
    total_cost: float

class TannersThirdAutoGeneratedTable_schema(BaseModel):
    tech_name: str
    job_number: str
    purchase_date: date
    vendor: str
    tax: float
    subtotal: float
    total_cost: float
